#############################
# Accelerator Software Settings
#############################

DEFINES += GP0_ADDR_BASE=0x43C00000
DEFINES += GP0_HIER_BASE=bsg_nonsynth_zynq_testbench.axil0
DEFINES += GP1_ADDR_BASE=0x80000000
DEFINES += GP1_HIER_BASE=bsg_nonsynth_zynq_testbench.axil1

include ../Makefile.design

