#ifndef PS_HPP
#define PS_HPP

// AXI_GP0 Read Memory Map
#define AXI_GP0_RD_CSR_RESET        (    GP0_ADDR_BASE                 )
#define AXI_GP0_RD_PL2PS_FIFO_DATA  (AXI_GP0_RD_CSR_RESET         + 0x4)
#define AXI_GP0_RD_PL2PS_FIFO_CTRS  (AXI_GP0_RD_PL2PS_FIFO_DATA   + 0x4)
#define AXI_GP0_RD_PS2PL_FIFO_CTRS  (AXI_GP0_RD_PL2PS_FIFO_CTRS   + 0x4)
#define AXI_GP0_RD_CSR_LAST_ADDR    (AXI_GP0_RD_PS2PL_FIFO_CTRS   + 0x4)

// AXI_GP0 Write Memory Map
#define AXI_GP0_WR_CSR_RESET          AXI_GP0_RD_CSR_RESET
#define AXI_GP0_WR_PS2PL_FIFO_DATA   (AXI_GP0_WR_CSR_RESET + 0x4)

// UART_GP0 Read Memory Map
#define UART_GP0_RD_CSR_LOOP_REG     (     GP0_ADDR_BASE                 )
#define UART_GP0_RD_PL2PS_FIFO_DATA  (UART_GP0_RD_CSR_LOOP_REG      + 0x4)
#define UART_GP0_RD_PL2PS_FIFO_CTRS  (UART_GP0_RD_PL2PS_FIFO_DATA   + 0x4)
#define UART_GP0_RD_PS2PL_FIFO_CTRS  (UART_GP0_RD_PL2PS_FIFO_CTRS   + 0x4)
#define UART_GP0_RD_CSR_LOOP_IN      (UART_GP0_RD_PS2PL_FIFO_CTRS   + 0x4)

// AXI_GP0 Write Memory Map
#define UART_GP0_WR_CSR_LOOP_REG       UART_GP0_RD_CSR_LOOP_REG
#define UART_GP0_WR_PS2PL_FIFO_DATA   (UART_GP0_WR_CSR_LOOP_REG + 0x4)

#endif

