
##########################################################
## User configuration
##########################################################
# boards: ultra96v2, pynqz2, vu47p
# hosts : zynq, bridge
export BOARDNAME ?= pynqz2
ifeq ($(BOARDNAME),ultra96v2)
export PART ?= xczu3eg-sbva484-1-e
export HOST ?= zynq
else ifeq ($(BOARDNAME),pynqz2)
export PART ?= xc7z020clg400-1
export HOST ?= zynq
else ifeq ($(BOARDNAME),vu47p)
export PART ?= xcvu47p-fsvh2892-3-e
export HOST ?= bridge
else
$(error Invalid BOARDNAME)
endif

