#ifndef PS_HPP
#define PS_HPP

// GP0 Read Memory Map
#define GP0_RD_CSR_SYS_RESETN    (GP0_ADDR_BASE                 )
#define GP0_RD_CSR_TAG_BITBANG   (GP0_RD_CSR_SYS_RESETN    + 0x4)
#define GP0_RD_CSR_DRAM_INITED   (GP0_RD_CSR_TAG_BITBANG   + 0x4)
#define GP0_RD_CSR_DRAM_BASE     (GP0_RD_CSR_DRAM_INITED   + 0x4)
#define GP0_RD_CSR_SAMPLE_GATE_EN (GP0_RD_CSR_DRAM_BASE     + 0x4)
#define GP0_RD_CSR_DRAM_GATE_EN  (GP0_RD_CSR_SAMPLE_GATE_EN + 0x4)
#define GP0_RD_CSR_SAMPLE_INTRVL (GP0_RD_CSR_DRAM_GATE_EN  + 0x4)
#define GP0_RD_CSR_DRAM_LATENCY  (GP0_RD_CSR_SAMPLE_INTRVL + 0x4)
#define GP0_RD_CSR_PROF_EN       (GP0_RD_CSR_DRAM_LATENCY  + 0x4)
#define GP0_RD_PL2PS_FIFO_0_DATA (GP0_RD_CSR_PROF_EN       + 0x4)
#define GP0_RD_PL2PS_FIFO_1_DATA (GP0_RD_PL2PS_FIFO_0_DATA + 0x4)
#define GP0_RD_PL2PS_FIFO_2_DATA (GP0_RD_PL2PS_FIFO_1_DATA + 0x4)
#define GP0_RD_PL2PS_FIFO_3_DATA (GP0_RD_PL2PS_FIFO_2_DATA + 0x4)
#define GP0_RD_PL2PS_FIFO_0_CTRS (GP0_RD_PL2PS_FIFO_3_DATA + 0x4)
#define GP0_RD_PL2PS_FIFO_1_CTRS (GP0_RD_PL2PS_FIFO_0_CTRS + 0x4)
#define GP0_RD_PL2PS_FIFO_2_CTRS (GP0_RD_PL2PS_FIFO_1_CTRS + 0x4)
#define GP0_RD_PL2PS_FIFO_3_CTRS (GP0_RD_PL2PS_FIFO_2_CTRS + 0x4)
#define GP0_RD_PS2PL_FIFO_CTRS   (GP0_RD_PL2PS_FIFO_3_CTRS + 0x4)
#define GP0_RD_REGS              (GP0_RD_PS2PL_FIFO_CTRS   + 0x4)
#define GP0_RD_MEM_PROF_0        (GP0_RD_REGS)
#define GP0_RD_MEM_PROF_1        (GP0_RD_MEM_PROF_0        + 0x4)
#define GP0_RD_MEM_PROF_2        (GP0_RD_MEM_PROF_1        + 0x4)
#define GP0_RD_MEM_PROF_3        (GP0_RD_MEM_PROF_2        + 0x4)
#define GP0_RD_MCYCLE            (GP0_RD_MEM_PROF_3        + 0x4)
#define GP0_RD_MINSTRET          (GP0_RD_MCYCLE            + 0x8)
#define GP0_RD_COUNTERS          (GP0_RD_MINSTRET          + 0x8)

// GP0 Write Memory Map
#define GP0_WR_CSR_SYS_RESETN    GP0_RD_CSR_SYS_RESETN
#define GP0_WR_CSR_TAG_BITBANG   GP0_RD_CSR_TAG_BITBANG
#define GP0_WR_CSR_DRAM_INITED   GP0_RD_CSR_DRAM_INITED
#define GP0_WR_CSR_DRAM_BASE     GP0_RD_CSR_DRAM_BASE
#define GP0_WR_CSR_SAMPLE_GATE_EN GP0_RD_CSR_SAMPLE_GATE_EN
#define GP0_WR_CSR_DRAM_GATE_EN  GP0_RD_CSR_DRAM_GATE_EN
#define GP0_WR_CSR_SAMPLE_INTRVL GP0_RD_CSR_SAMPLE_INTRVL
#define GP0_WR_CSR_DRAM_LATENCY  GP0_RD_CSR_DRAM_LATENCY
#define GP0_WR_CSR_PROF_EN       GP0_RD_CSR_PROF_EN
#define GP0_WR_PS2PL_FIFO_DATA   (GP0_WR_CSR_DRAM_LATENCY + 0x4)

// DRAM
#define DRAM_BASE_ADDR  0x80000000U
#define DRAM_MAX_ALLOC_SIZE 0x20000000U
// GP1
#define GP1_DRAM_BASE_ADDR GP1_ADDR_BASE
#define GP1_CSR_BASE_ADDR (GP1_DRAM_BASE_ADDR + DRAM_MAX_ALLOC_SIZE)

#define TAG_NUM_CLIENTS 16
#define TAG_MAX_LEN 1
#define TAG_CLIENT_PL_RESET_ID 0
#define TAG_CLIENT_PL_RESET_WIDTH 1
#define TAG_CLIENT_WD_RESET_ID 1
#define TAG_CLIENT_WD_RESET_WIDTH 1

#endif

