TOP  := $(shell git rev-parse --show-toplevel)
CURR := $(shell pwd)
include $(TOP)/Makefile.common

#############################
# Design Settings
#############################
BOARDNAME  ?= pynqz2
TOP_MODULE ?= top
BASENAME   ?= blackparrot

#############################
# Run Collateral for example
#############################
%.nbf:
	$(MAKE) -C $(SOFTWARE_DIR) $(@F)
	mv $(SOFTWARE_DIR)/$(@F) $@

RUN_COLLATERAL = $(NBF_FILE)

