#ifndef PS_HPP
#define PS_HPP

// GP0 Read Memory Map
#define GP0_RD_CSR_SYS_RESETN     (GP0_ADDR_BASE                    )
#define GP0_RD_CSR_DRAM_INITED    (GP0_RD_CSR_SYS_RESETN     + 0x4  )
#define GP0_RD_CSR_DRAM_BASE      (GP0_RD_CSR_DRAM_INITED    + 0x4  )
#define GP0_RD_CSR_BOOTROM_ADDR   (GP0_RD_CSR_DRAM_BASE      + 0x4  )
#define GP0_RD_CSR_DEBUG_IRQ      (GP0_RD_CSR_BOOTROM_ADDR   + 0x4  )
#define GP0_RD_CSR_TIMER_IRQ      (GP0_RD_CSR_DEBUG_IRQ      + 0x4  )
#define GP0_RD_CSR_SOFTWARE_IRQ   (GP0_RD_CSR_TIMER_IRQ      + 0x4  )
#define GP0_RD_CSR_M_EXTERNAL_IRQ (GP0_RD_CSR_SOFTWARE_IRQ   + 0x4  )
#define GP0_RD_CSR_S_EXTERNAL_IRQ (GP0_RD_CSR_M_EXTERNAL_IRQ + 0x4  )
#define GP0_RD_CSR_FREEZEN        (GP0_RD_CSR_S_EXTERNAL_IRQ + 0x4  )
#define GP0_RD_PL2PS_FIFO_DATA    (GP0_RD_CSR_FREEZEN        + 0x4  )
#define GP0_RD_PL2PS_FIFO_CTRS    (GP0_RD_PL2PS_FIFO_DATA    + 0x4*2)
#define GP0_RD_PS2PL_FIFO_CTRS    (GP0_RD_PL2PS_FIFO_CTRS    + 0x4*2)
#define GP0_RD_CREDITS            (GP0_RD_PS2PL_FIFO_CTRS    + 0x4*2)
#define GP0_RD_MINSTRET           (GP0_RD_CREDITS            + 0x4  )
#define GP0_RD_MINSTRET_0         (GP0_RD_MINSTRET                  )
#define GP0_RD_MINSTRET_1         (GP0_RD_MINSTRET_0         + 0x4  )
#define GP0_RD_BOOTROM_DATA       (GP0_RD_MINSTRET_1         + 0x4  )

// GP0 Write Memory Map
#define GP0_WR_CSR_SYS_RESETN     GP0_RD_CSR_SYS_RESETN
#define GP0_WR_CSR_DRAM_INITED    GP0_RD_CSR_DRAM_INITED
#define GP0_WR_CSR_DRAM_BASE      GP0_RD_CSR_DRAM_BASE
#define GP0_WR_CSR_BOOTROM_ADDR   GP0_RD_CSR_BOOTROM_ADDR
#define GP0_WR_CSR_DEBUG_IRQ      GP0_RD_CSR_DEBUG_IRQ
#define GP0_WR_CSR_TIMER_IRQ      GP0_RD_CSR_TIMER_IRQ
#define GP0_WR_CSR_SOFTWARE_IRQ   GP0_RD_CSR_SOFTWARE_IRQ
#define GP0_WR_CSR_M_EXTERNAL_IRQ GP0_RD_CSR_M_EXTERNAL_IRQ
#define GP0_WR_CSR_S_EXTERNAL_IRQ GP0_RD_CSR_S_EXTERNAL_IRQ
#define GP0_WR_CSR_FREEZEN        GP0_RD_CSR_FREEZEN
#define GP0_WR_PS2PL_FIFO_DATA   (GP0_WR_CSR_FREEZEN + 0x4)

// DRAM
#define DRAM_BASE_ADDR  0x80000000U
#define DRAM_MAX_ALLOC_SIZE 0x20000000U

// BP
#define BP_MTIME    0x30bff8
#define BP_MTIMECMP 0x304000

#endif

