TOP ?= $(shell git rev-parse --show-toplevel)
include $(TOP)/Makefile.common
include $(TOP)/Makefile.env

#############################
# Accelerator Software Settings
#############################
include $(DESIGN_DIR)/Makefile.design
include $(COSIM_MK_DIR)/Makefile.vivado

