
#############################
# Design Settings
#############################
TB_MODULE  ?= null
BASENAME   ?= axi3

MAIN_PROGRAM ?= $(COSIM_CSRC_DIR)/main.cpp
HOST_PROGRAM ?= $(DESIGN_DIR)/ps.cpp

ZYNQ_PL_DEBUG ?= 0
ZYNQ_PS_DEBUG ?= 0

#############################
# Design Defines
#############################
DEFINES += GP0_ENABLE=1
DEFINES += GP0_ADDR_WIDTH=6 GP0_DATA_WIDTH=32
DEFINES += ACLK_MHZ=200

include $(DESIGN_DIR)/Makefile.hardware

