
#############################
# Accelerator Software Settings
#############################
#CFLAGS += -DZYNQ_PL_DEBUG
#CFLAGS += -DZYNQ_PS_DEBUG
#CFLAGS += -DVERIFY_NBF

DEFINES += NUM_FINISH=1
DEFINES += GP0_ADDR_BASE=0x40000000U
DEFINES += GP0_HIER_BASE=bsg_nonsynth_zynq_testbench.axil0
DEFINES += HP0_ADDR_BASE=0x00000000U
DEFINES += AXI_MEM_ENABLE

include ../Makefile.design

