# MBT
# instructions: as root create the directory, which sh

all:
	@echo "make <version>.install"
	@echo i.e. make v4.202.install


# e.g. make v4.202.install
%.install:
	sudo /bin/bash -c "mkdir -p $*; chown $$USER $*; chgrp $$USER $*"
	cd $*; git clone https://github.com/verilator/verilator; cd verilator; git pull; git checkout $*;
	cd $*; cd verilator; export VERILATOR_ROOT=`pwd`; autoconf; ./configure; make -j 20


