TOP  := $(shell git rev-parse --show-toplevel)
CURR := $(shell pwd)
include $(TOP)/Makefile.common

#############################
# Design Settings
#############################
TOP_MODULE ?= top
BOARDNAME  ?= pynqz2
BASENAME   ?= simple

