
#############################
# Accelerator Software Settings
#############################
DEFINES += HP1_ADDR_BASE=0x0000000
DEFINES += HP1_HIER_BASE=TOP.bsg_nonsynth_zynq_testbench.axil4

include ../Makefile.design

