#############################
# Accelerator Software Settings
#############################
DEFINES += GP0_ADDR_BASE=0x43C00000
DEFINES += GP0_HIER_BASE=bsg_nonsynth_zynq_testbench.axil0

include ../Makefile.design

