
#############################
# Accelerator Software Settings
#############################

DEFINES += GP0_ADDR_BASE=0x40000000
DEFINES += GP0_HIER_BASE=TOP.bsg_nonsynth_zynq_testbench.axil0
DEFINES += HP0_ADDR_BASE=0x00000000U
DEFINES += AXI_MEM_ENABLE

include ../Makefile.design

