TOP  := $(shell git rev-parse --show-toplevel)
CURR := $(shell pwd)
include $(TOP)/Makefile.common

#############################
# Design Settings
#############################
HOST       ?= zynq
BOARDNAME  ?= pynqz2
TOP_MODULE ?= top
BASENAME   ?= shell

MAIN_PROGRAM ?= $(COSIM_CSRC_DIR)/main.cpp
HOST_PROGRAM ?= $(CURR_DESIGN_DIR)/ps.cpp

