
#############################
# Accelerator Software Settings
#############################
CFLAGS += -mfpu=neon

DEFINES += GP0_ADDR_SIZE_BYTES=4096
DEFINES += GP1_ADDR_SIZE_BYTES=4096
DEFINES += NEON

include ../Makefile.design

