#ifndef PS_HPP

// GP0 Read Memory Map
#define GP0_RD_CSR_DRAM_BASE_ADDR       (GP0_ADDR_BASE                       )
#define GP0_RD_PL2PS_FIFO_RESP_DATA     (GP0_RD_CSR_DRAM_BASE_ADDR      + 0x4)
#define GP0_RD_PL2PS_FIFO_RESP_CNTR     (GP0_RD_PL2PS_FIFO_RESP_DATA    + 0x4)
#define GP0_RD_PS2PL_FIFO_REQ_TYPE_CNTR (GP0_RD_PL2PS_FIFO_RESP_CNTR    + 0x4)
#define GP0_RD_PS2PL_FIFO_REQ_ADDR_CNTR (GP0_RD_PS2PL_FIFO_REQ_TYPE_CNTR   + 0x4)
#define GP0_RD_PS2PL_FIFO_REQ_DATA_CNTR (GP0_RD_PS2PL_FIFO_REQ_ADDR_CNTR   + 0x4)
#define GP0_RD_CSR_WRITE_PROGRESS       (GP0_RD_PS2PL_FIFO_REQ_DATA_CNTR   + 0x4)

// GP0 Write Memory Map
#define GP0_WR_CSR_DRAM_BASE_ADDR       GP0_RD_CSR_DRAM_BASE_ADDR
#define GP0_WR_PS2PL_FIFO_REQ_TYPE      (GP0_WR_CSR_DRAM_BASE_ADDR  + 0x4)
#define GP0_WR_PS2PL_FIFO_REQ_ADDR      (GP0_WR_PS2PL_FIFO_REQ_TYPE + 0x4)
#define GP0_WR_PS2PL_FIFO_REQ_DATA      (GP0_WR_PS2PL_FIFO_REQ_ADDR + 0x4)

#endif

