TOP  := $(shell git rev-parse --show-toplevel)
CURR := $(shell pwd)
include $(TOP)/Makefile.common

#############################
# Design Settings
#############################
BOARDNAME  ?= pynqz2
TOP_MODULE ?= top
BASENAME   ?= hammerblade

#############################
# Run Collateral
#############################
%.nbf:
	$(MAKE) -C $(BSG_MANYCORE_SOFTWARE_DIR)/spmd/$* clean main.nbf
	mv $(BSG_MANYCORE_SOFTWARE_DIR)/spmd/$*/main.nbf $@

RUN_COLLATERAL = $(NBF_FILE)

