
#############################
# Environment Settings
#############################
# TCL to pause between stages, batch to proceed straight through
VIVADO_MODE        ?= batch
# These are set by bsg_cadenv but can be overridden
VIVADO_PATH        ?= /tools/Xilinx/Vivado
# current supported 2019.1 and 2022.1
VIVADO_VERSION     ?= 2022.1
# Path to specific Vivado install
XILINX_VIVADO      ?= $(VIVADO_PATH)/$(VIVADO_VERSION)
# update this with a pointer to your vivado install
VIVADO_SETTINGS    ?= $(XILINX_VIVADO)/settings64.sh
# Path to specific PetaLinux install
PETALINUX_PATH     ?= /tools/Xilinx/PetaLinux
# current supported 2019.1 and 2022.1
PETALINUX_VERSION  ?= 2022.1
# Path to specific Vivado install
XILINX_PETALINUX   ?= $(PETALINUX_PATH)/$(PETALINUX_VERSION)
# update this with a pointer to your vivado install
PETALINUX_SETTINGS ?= $(XILINX_PETALINUX)/settings.sh

VIVADO_RUN    ?= source $(VIVADO_SETTINGS) && $(VIVADO) -mode $(VIVADO_MODE)
PETALINUX_RUN ?= source $(PETALINUX_SETTINGS) && $(PETALINUX)

PYNQZ2_SDK  ?= $(SOFTWARE_INSTALL_DIR)/pynqz2
PYNQZ2_ENV  ?= $(PYNQZ2_SDK)/environment-setup-cortexa9t2hf-neon-xilinx-linux-gnueabi

ULTRA96V2_SDK  ?= $(SOFTWARE_INSTALL_DIR)/ultra96v2
ULTRA96V2_ENV  ?= $(ULTRA96V2_SDK)/environment-setup-cortexa72-cortexa53-xilinx-linux

