
#############################
# Accelerator Software Settings
#############################

DEFINES += GP0_ADDR_BASE=0x43C00000
DEFINES += GP0_HIER_BASE=bsg_nonsynth_zynq_testbench.axil0
DEFINES += HP0_ADDR_BASE=0x00000000U
DEFINES += AXI_MEM_ENABLE

VSOURCES += $(BASEJUMP_STL_DIR)/bsg_test/bsg_nonsynth_axi_mem.sv

include ../Makefile.design
