
ifneq (ultra96v2,$(BOARDNAME))
$(error Only ultra96v2 is supported for this target ($(BOARDNAME) given))
endif

#############################
# Accelerator Software Settings
#############################

include ../Makefile.design

